"""Initial models.

Revision ID: 7ab65242c3dd
Revises:
Create Date: 2026-03-28 15:59:37.840531

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7ab65242c3dd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
